import { handler as usageTrackerHandler } from "../lambda/usageTracker";
import { EventBridgeEvent } from "aws-lambda";

// Mock AWS services for integration testing
jest.mock("@aws-sdk/client-bedrock-runtime");
jest.mock("@aws-sdk/client-eventbridge");
jest.mock("../lib/utils/billingDatabase");

describe("Usage Tracker Integration", () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it("should handle bedrock.response events with expected structure", async () => {
    // This test verifies that the usage tracker can handle the event structure
    // that would be generated by analyzeDiff

    // Mock the billing database services
    const {
      UsageRecordsService,
      UserAccountsService,
      BillingUtils,
    } = require("../lib/utils/billingDatabase");

    UserAccountsService.getUserAccountByGitHub.mockResolvedValue({
      userId: "test-user-123",
      githubUsername: "testuser",
      email: "testuser@example.com",
      status: "active",
      usageLimits: {
        monthlyLimit: 1000,
        alertAt80Percent: true,
        suspendOnExceed: true,
      },
    });

    UsageRecordsService.recordUsage.mockResolvedValue();
    UsageRecordsService.getUserUsageCount.mockResolvedValue(50);
    BillingUtils.getCurrentBillingPeriod.mockReturnValue("2024-01");

    // Create a bedrock.response event with the structure that analyzeDiff would generate
    const bedrockResponseEvent: EventBridgeEvent<"bedrock.response", any> = {
      version: "0",
      id: "bedrock-response-123",
      "detail-type": "bedrock.response",
      source: "vortex.github",
      account: "123456789012",
      time: "2024-01-15T10:05:00Z",
      region: "us-east-1",
      resources: [],
      detail: {
        analysisResult: {
          content: [{ text: "This code looks good! No issues found." }],
        },
        eventId: "original-diff-event-123",
        repo: "test-org/test-repo",
        type: "commit",
        fileCount: 3,
        githubUsername: "testuser",
      },
    };

    // Process the usage tracking
    const usageResult = await usageTrackerHandler(bedrockResponseEvent);
    expect(usageResult.statusCode).toBe(200);
    expect(usageResult.message).toBe("Usage tracked successfully");

    // Verify that usage was recorded with correct data
    expect(UsageRecordsService.recordUsage).toHaveBeenCalledWith(
      expect.objectContaining({
        userId: "test-user-123",
        githubUsername: "testuser",
        eventType: "commit",
        eventId: "original-diff-event-123",
        repository: "test-org/test-repo",
        analysisSuccess: true,
        billingPeriod: "2024-01",
        eventMetadata: expect.objectContaining({
          fileCount: 3,
          originalEventId: "bedrock-response-123",
        }),
      })
    );
  });

  it("should handle event structure compatibility", () => {
    // This test ensures that the event structure from analyzeDiff
    // contains all the fields expected by usageTracker

    const mockAnalyzeDiffOutput = {
      analysisResult: { content: [{ text: "Analysis complete" }] },
      eventId: "original-event-123",
      repo: "test-org/test-repo",
      type: "commit",
      fileCount: 3,
      githubUsername: "testuser",
    };

    // Verify all required fields are present
    expect(mockAnalyzeDiffOutput).toHaveProperty("eventId");
    expect(mockAnalyzeDiffOutput).toHaveProperty("repo");
    expect(mockAnalyzeDiffOutput).toHaveProperty("type");
    expect(mockAnalyzeDiffOutput).toHaveProperty("githubUsername");
    expect(mockAnalyzeDiffOutput).toHaveProperty("fileCount");

    // Verify event type is valid
    expect(["commit", "pull_request"]).toContain(mockAnalyzeDiffOutput.type);
  });

  it("should handle missing optional fields gracefully", async () => {
    const mockEvent: EventBridgeEvent<"bedrock.response", any> = {
      version: "0",
      id: "test-event-id",
      "detail-type": "bedrock.response",
      source: "vortex.github",
      account: "123456789012",
      time: "2024-01-15T10:00:00Z",
      region: "us-east-1",
      resources: [],
      detail: {
        analysisResult: { content: [{ text: "Analysis complete" }] },
        eventId: "original-event-123",
        repo: "test-org/test-repo",
        type: "commit",
        githubUsername: "testuser",
        // fileCount is missing - should handle gracefully
      },
    };

    // Mock the billing database services
    const {
      UsageRecordsService,
      UserAccountsService,
      BillingUtils,
    } = require("../lib/utils/billingDatabase");

    UserAccountsService.getUserAccountByGitHub.mockResolvedValue({
      userId: "test-user-123",
      githubUsername: "testuser",
      status: "active",
      usageLimits: { monthlyLimit: 1000 },
    });

    UsageRecordsService.recordUsage.mockResolvedValue();
    UsageRecordsService.getUserUsageCount.mockResolvedValue(50);
    BillingUtils.getCurrentBillingPeriod.mockReturnValue("2024-01");

    const result = await usageTrackerHandler(mockEvent);
    expect(result.statusCode).toBe(200);

    // Should still record usage even with missing fileCount
    expect(UsageRecordsService.recordUsage).toHaveBeenCalledWith(
      expect.objectContaining({
        eventMetadata: expect.objectContaining({
          fileCount: undefined, // Should handle undefined gracefully
        }),
      })
    );
  });
});
